// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz_-mI5PvhIFofqdIYHXv1r1lswsvjIW8',
    appId: '1:689102902761:web:bdfc000620be4ef639e778',
    messagingSenderId: '689102902761',
    projectId: 'medical-data-storage-316cf',
    authDomain: 'medical-data-storage-316cf.firebaseapp.com',
    storageBucket: 'medical-data-storage-316cf.appspot.com',
    measurementId: 'G-CP2Z1G2819',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_sE4_QrE6_tUl0L8qCPuK8M5wmdhYkA',
    appId: '1:689102902761:android:9804f905b732261439e778',
    messagingSenderId: '689102902761',
    projectId: 'medical-data-storage-316cf',
    storageBucket: 'medical-data-storage-316cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsj5cTeRRUIibHhxRNkNN49gO4dUAtcSU',
    appId: '1:689102902761:ios:2362493eaf7a517939e778',
    messagingSenderId: '689102902761',
    projectId: 'medical-data-storage-316cf',
    storageBucket: 'medical-data-storage-316cf.appspot.com',
    iosClientId: '689102902761-kf35g7v7j2n2rliqk3agcr5nk8qhto8g.apps.googleusercontent.com',
    iosBundleId: 'com.sample.documentStorage',
  );
}
